### ISSUE TITLE
Needed use case - recurring every weekday

### ISSUE THREAD

**Issue by solscher** [logicsquad/recurring#4]
Would love to use this library but missing one important use case:

Recurring every weekday, e.g.

- Every Monday
- Every second Monday
- Every Monday and every Thursday
- Every (third) Monday in June, July, August 2024

and so on.

**Comment by paulhoadley** [comment]
Hi @solscher,

> Every Monday

We can certainly add a `DayInWeek` class that just takes a `java.time.DayOfWeek`.

> Every second Monday

We could do this as a variant of `DayInWeek`, but it would need a "start date"—some Monday that was in the sequence, from which you measure "every second Monday".

> Every Monday and every Thursday

Once we have `DayInWeek`, they're easily combined with `Union`.

> Every (third) Monday in June, July, August 2024

This you can already do:

```
DayInMonth thirdMonday = DayInMonth.of(DayOfWeek.MONDAY, 3);
RangeEveryYear juneJulyAugust = RangeEveryYear.of(Month.JUNE, Month.AUGUST);
TemporalExpression thirdMondayInJuneJulyAugust = Intersection.of(thirdMonday, juneJulyAugust);
Schedule schedule = Schedule.of(ScheduleElement.of("issue2", thirdMondayInJuneJulyAugust));
List<LocalDate> datesIn2024 = schedule.datesInRange("issue2", LocalDate.of(2024, 1, 1), LocalDate.of(2024, 12, 31));
```

**Comment by paulhoadley** [comment]
Have a look at the latest commits to `develop`. We can now do all of your use cases.

* Every Monday: `DayInWeek.of(DayOfWeek.MONDAY)`
* Every second Monday [from, say, 2023-08-14]: `DayInWeek.of(2, LocalDate.of(2023, 8, 14))`
* Every Monday and every Thursday: `Union.of(DayInWeek.of(DayOfWeek.MONDAY), DayInWeek.of(DayOfWeek.THURSDAY))`
* Every (third) Monday in June, July, August 2024: as above.

**Comment by paulhoadley** [comment]
If you verify that this works for you, and the fix for #5, I can roll a release tomorrow.

**Comment by dogfellow** [comment]
A release would be great. Thanks for implementing.

**Comment by solscher** [comment]
A release would be great. Thanks for implementing.
