### ISSUE TITLE
1st September example is not working

### ISSUE THREAD

**Issue by solscher** [logicsquad/recurring#5]
The mentioned recurring of 1st September is not working for me. Short exchange with Paul leads to the following result:

Use case: Every date in year - E.g. 1st September 2023, 1st September 2024, 1st September 2025, and so on

```
TemporalExpression range = RangeEveryYear.of(MonthDay.of(Month.SEPTEMBER, 1), MonthDay.of(Month.SEPTEMBER, 1));
```

is not working, a it seems to provide a range from 1 September to 1 September in the following year (and then onwards, of course), so every day in the year.

**Comment by paulhoadley** [comment]
This is definitely a bug, and being unable to represent a _single day_ is just a specific example of a wider problem: `RangeEveryYear` would appear to be broken for all ranges where the start end months _are the same month._

**Comment by paulhoadley** [comment]
Fixed.
